namespace Crayon
{
	internal enum FrameworkFunction
	{
		IO_CURRENT_DIRECTORY,
		IO_DIRECTORY_LISTING,
		IO_FILE_READ_TEXT,
		IO_FILE_WRITE_TEXT,
		IO_IS_PATH_DIRECTORY,
		IO_PATH_EXISTS,
		IO_PATH_JOIN,

		MUSIC_LOAD_FROM_FILE,
		MUSIC_LOAD_FROM_RESOURCE,
		MUSIC_LOAD_FROM_USER_DATA,
		MUSIC_LOAD_FROM_WEB,
		MUSIC_GET_POSITION,
		MUSIC_GET_CURRENT,
		MUSIC_GET_MASTER_VOLUME,
		MUSIC_PAUSE,
		MUSIC_PLAY,
		MUSIC_RESUME,
		MUSIC_SET_POSITION,
		MUSIC_SET_VOLUME,
		MUSIC_SET_MASTER_VOLUME,
		MUSIC_STOP,
		
		SFX_GET_MASTER_VOLUME,
		SFX_LOAD_FROM_FILE,
		SFX_LOAD_FROM_RESOURCE,
		SFX_LOAD_FROM_USER_DATA,
		SFX_LOAD_FROM_WEB,
		SFX_PAUSE,
		SFX_PLAY,
		SFX_STOP,
		SFX_SET_MASTER_VOLUME,
		SFX_SET_VOLUME,

		USER_DATA_DELETE_DIRECTORY,
		USER_DATA_DELETE_FILE,
		USER_DATA_DIRECTORY_LISTING,
		USER_DATA_FILE_READ_TEXT,
		USER_DATA_FILE_WRITE_TEXT,
		USER_DATA_MAKE_DIRECTORY,
		USER_DATA_IS_PATH_DIRECTORY,
		USER_DATA_PATH_EXISTS,
	}
}
