namespace Crayon
{
	internal enum FrameworkFunction
	{
		ABS = 1,
		ARCCOS,
		ARCSIN,
		ARCTAN,
		ARCTAN2,
		ASSERT,
		COS,
		CURRENT_TIME,
		FLOOR,

		GAME_CLOCK_TICK,
		GAME_INITIALIZE,
		GAME_INITIALIZE_SCREEN,
		GAME_INITIALIZE_SCREEN_SCALED,
		GAME_PUMP_EVENTS,
		GAME_SET_TITLE,
		
		GFX_BLIT_IMAGE,
		GFX_BLIT_IMAGE_PARTIAL,
		GFX_DRAW_ELLIPSE,
		GFX_DRAW_LINE,
		GFX_DRAW_RECTANGLE,
		GFX_FILL_SCREEN,
		GFX_FLIP_IMAGE,
		GFX_IMAGE_ERROR_CODE,
		GFX_IMAGE_GET,
		GFX_IMAGE_LOAD_FROM_RESOURCE,
		GFX_IMAGE_LOAD_FROM_WEB,
		GFX_IMAGE_LOAD_FROM_USER_DATA,
		GFX_IMAGE_POP_SCALE,
		GFX_IMAGE_PUSH_SCALE,
		GFX_IMAGE_SHEET_ERROR_CODE,
		GFX_IMAGE_SHEET_LOAD,
		GFX_IMAGE_SHEET_LOAD_PROGRESS,
		GFX_IMAGE_SHEET_LOADED,
		GFX_IS_IMAGE_LOADED,

		PARSE_INT,
		
		PARSE_JSON,
		PRINT,
		RANDOM,
		RESOURCE_READ_TEXT,
		SIN,
		TAN,
		TYPEOF,
	}
}
