namespace Crayon
{
	internal enum FrameworkFunction
	{
		ABS = 1,
		ARCTAN2,
		ASSERT,
		BLIT_IMAGE,
		CLOCK_TICK,
		COS,
		CURRENT_TIME,
		DOWNLOAD_IMAGE,
		DRAW_ELLIPSE,
		DRAW_LINE,
		DRAW_RECTANGLE,
		FILL_SCREEN,
		FLIP_IMAGE,
		FLOOR,
		GET_EVENTS,
		GET_IMAGE,
		GET_IMAGE_HEIGHT,
		GET_IMAGE_WIDTH,
		INITIALIZE_GAME,
		INITIALIZE_SCREEN,
		INITIALIZE_SCREEN_SCALED,
		IS_IMAGE_LOADED,
		PARSE_INT,
		PRINT,
		RANDOM,
		SET_TITLE,
		SIN,
		TYPEOF,
	}
}
