namespace Crayon
{
	internal enum PrimitiveMethods
	{
		STRING_LOWER = 1,
		STRING_REPLACE = 2,
		STRING_SPLIT = 3,
		STRING_TRIM = 4,
		STRING_UPPER = 5,

		LIST_ADD = 6,
		LIST_CLEAR = 7,
		LIST_CONTAINS = 8,
		LIST_INSERT = 9,
		LIST_POP = 10,
		LIST_REVERSE = 11,

		DICTIONARY_ADD = 12,
		DICTIONARY_CLEAR = 13,
		DICTIONARY_CONTAINS = 14,
		DICTIONARY_ENTRIES = 15,
		DICTIONARY_REMOVE = 16,
		DICTIONARY_VALUES = 17,
	}
}
