namespace Crayon
{
	internal enum PrimitiveMethods
	{
		STRING_CONTAINS = 1,
		STRING_ENDSWITH,
		STRING_LOWER,
		STRING_REPLACE,
		STRING_REVERSE,
		STRING_SPLIT,
		STRING_STARTSWITH,
		STRING_TRIM,
		STRING_UPPER,

		LIST_ADD,
		LIST_CLEAR,
		LIST_CONTAINS,
		LIST_INSERT,
		LIST_POP,
		LIST_REMOVE,
		LIST_REVERSE,

		DICTIONARY_CLEAR,
		DICTIONARY_CONTAINS,
		DICTIONARY_ENTRIES,
		DICTIONARY_KEYS,
		DICTIONARY_REMOVE,
		DICTIONARY_VALUES,
	}
}
